wildfly:
  rules:
    - id: lra
      titleBody: "lra"
      directories:
        - microprofile/lra
      notify: [xstefank, nonexistentaccount]
    - id: health
      titleBody: "health"
      directories:
        - microprofile/health-smallrye
        - health
      notify: [xstefank, nonexistentaccount]
  format:
    title-check:
      pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
      message: "Wrong content of the title!"
    description:
      regexes:
        - pattern: "JIRA:\\s+https://issues.redhat.com/browse/WFLY-\\d+|https://issues.redhat.com/browse/WFLY-\\d+"
          message: "The PR description must contain a link to the JIRA issue"
    commits-message:
      pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
      message: "Wrong commit message, needs to be in format of 'WFLY-XYZ|[WFLY-XYZ] ...'"
    commits-quantity:
      quantity: "1-3"
      message: "Too many commits in PR!"
  emails:
    - xstefank122@gmail.com
